version: '2'
services:
  mongodb:
    build: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    container_name: mongodb
  nodejs:
    build: nodejs
    expose:
      - 8000
      - 8001
    ports:
      - 8000:8000
      - 8001:8001
    container_name: nodejs