version: '2'
volumes:
  postgres_data:
    driver: local
services:
  mongodb:
    build: mongodb
    volumes:
      - ./mongodb/shared:/shared
    expose:
      - 27017
    ports:
      - 27017:27017
    container_name: mongodb
  postgres:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    container_name: postgres
  neo4j:
    build: neo4j
    volumes: 
      - ./neo4j/shared/data:/data
    expose:
      - 7474
      - 7473
      - 7687
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    container_name: neo4j
  # nodejs:
  #   build: nodejs
  #   expose:
  #     - 8000
  #     - 8001
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #   container_name: nodejs