version: '2'
services:
  mongodb:
    build: mongodb
    volumes:
      - ./mongodb/shared:/shared
    expose:
      - 27017
    ports:
      - 27017:27017
    container_name: mongodb
  postgres:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    expose:
      - 5432
    ports:
      - 5432:5432
    container_name: postgres

  # nodejs:
  #   build: nodejs
  #   expose:
  #     - 8000
  #     - 8001
  #   ports:
  #     - 8000:8000
  #     - 8001:8001
  #   container_name: nodejs